# Generated by Django 4.0.5 on 2022-06-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtpiitdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta_ship',
            name='chair_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='comments_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='ldap_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='reco_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='src_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='src_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='src_form',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='supervisor_0',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='supervisor_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='supervisor_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='ta_course',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='ta_entry',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='ta_user',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='topic_n',
            field=models.CharField(max_length=200),
        ),
    ]
