# Generated by Django 4.0.5 on 2022-06-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtpiitdapp', '0002_alter_ta_ship_chair_name_alter_ta_ship_comments_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta_shipnew',
            name='ta_entry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
